# Site settings
title: Thomas Bassetto
email: tbassetto@gmail.com
description: UI Engineer, with a focus on web technologies. Google Developer Expert Web Technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomasbassetto.com" # the base hostname & protocol for your site
twitter_username: tbassetto
github_username:  tbassetto

permalink: /blog/:title/
lsi: true

include: ["_pages"]
exclude: [".editorconfig", ".gitignore", "Gemfile", "Gemfile.lock", "Makefile", "README.md"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
