# Site settings
title: Thomas Bassetto
email: tbassetto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, with a focus on web technologies. Google Developer Expert Chrome: HTML5.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thomasbassetto.com" # the base hostname & protocol for your site
twitter_username: tbassetto
github_username:  tbassetto

permalink: /blog/:title/
lsi: true

include: ["_pages"]
exclude: [".editorconfig", ".gitignore", "Gemfile", "Gemfile.lock", "Makefile", "README.md"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
