# Site settings
title: Thomas Bassetto
description: "Senior Software Engineer at DNV"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomasbassetto.com" # the base hostname & protocol for your site
twitter_username: tbassetto
github_username:  tbassetto

permalink: /blog/:title/
lsi: true

exclude: [".editorconfig", ".gitignore", "Gemfile", "Gemfile.lock", "Makefile", "README.md"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
